return {
  file = {
    file = '',
    modified = '',
    readonly = '',
    new = '',
  },
  folder = {
    closed = '',
    open = '',
    empty = '󰜌',
    collapsed = '',
    expanded = '',
  },
  dap = {
    DapBreakpoint = '',
    DapBreakpointCondition = '',
    DapBreakpointRejected = '',
    DapLogPoint = '󰌑',
    DapStopped = '',
  },
  diagnostics = {
    DiagnosticSignError = '●',
    DiagnosticSignWarn = '●',
    DiagnosticSignInfo = '●',
    DiagnosticSignHint = '○',
  },
  subscript_count = {
    '⒈',
    '⒉',
    '⒊',
    '⒋',
    '⒌',
    '⒍',
    '⒎',
    '⒏',
    '⒐',
    '⒑',
    '⒒',
    '⒓',
    '⒔',
    '⒕',
    '⒖',
    '⒗',
    '⒘',
    '⒙',
    '⒚',
    '⒛',
  },
  completion_source = {
    nvim_lsp = '󰞵',
    nvim_lua = '',
    treesitter = '',
    path = '󰝰',
    buffer = '󱈛',
    zsh = '',
    vsnip = '',
    spell = '󰓆',
  },
}
