local Color, colors, Group, groups, styles = require('colorbuddy').setup()

vim.cmd("hi! clear")

local globals = {
  background = 'dark',
  colors_name = 'onedark',
  terminal_color_0  = '#353a44',
  terminal_color_8  = '#353a44',
  terminal_color_1  = '#e88388',
  terminal_color_9  = '#e88388',
  terminal_color_2  = '#a7cc8c',
  terminal_color_10 = '#a7cc8c',
  terminal_color_3  = '#ebca8d',
  terminal_color_11 = '#ebca8d',
  terminal_color_4  = '#72bef2',
  terminal_color_12 = '#72bef2',
  terminal_color_5  = '#d291e4',
  terminal_color_13 = '#d291e4',
  terminal_color_6  = '#65c2cd',
  terminal_color_14 = '#65c2cd',
  terminal_color_7  = '#e3e5e9',
  terminal_color_15 = '#e3e5e9',
}

for key, value in pairs(globals) do
  vim.g[key] = value
end

Color.new('mono_1',        '#abb2bf')
Color.new('mono_2',        '#828997')
Color.new('mono_3',        '#5c6370')
Color.new('mono_4',        '#4b5263')
Color.new('hue_1',         '#56b6c2')
Color.new('hue_2',         '#61afef')
Color.new('hue_3',         '#c678dd')
Color.new('hue_4',         '#98c379')
Color.new('hue_5',         '#e06c75')
Color.new('hue_5_2',       '#be5046')
Color.new('hue_6',         '#d19a66')
Color.new('hue_6_2',       '#e5c07b')
Color.new('syntax_bg',     '#282c34')
--Color.new('syntax_bg',     '#303030')
Color.new('syntax_fg',     '#abb2bf')
Color.new('syntax_fold_bg','#5c6370')
Color.new('syntax_gutter', '#636d83')
Color.new('syntax_cursor', '#2c323c')
Color.new('syntax_accent', '#528bff')
Color.new('vertsplit',     '#181a1f')
Color.new('special_grey',  '#3b4048')
Color.new('visual_grey',   '#3e4452')
Color.new('pmenu',         '#333841')

-- Vim editor color
Group.new('Normal',       colors.syntax_fg,     colors.syntax_bg,      styles.NONE)
Group.new('bold',         colors.none,          colors.none,           styles.bold)
Group.new('ColorColumn',  colors.none,          colors.syntax_cursor,  styles.NONE)
Group.new('Conceal',      colors.mono_4,        colors.syntax_bg,      styles.NONE)
Group.new('Cursor',       colors.none,          colors.syntax_accent,  styles.NONE)
Group.new('CursorIM',     colors.none,          colors.none,           styles.NONE)
Group.new('CursorColumn', colors.none,          colors.syntax_cursor,  styles.NONE)
Group.new('CursorLine',   colors.none,          colors.syntax_cursor,  styles.NONE)
Group.new('Directory',    colors.hue_2,         colors.none,           styles.NONE)
Group.new('ErrorMsg',     colors.hue_5,         colors.syntax_bg,      styles.NONE)
Group.new('VertSplit',    colors.vertsplit,     colors.none,           styles.NONE)
Group.new('Folded',       colors.syntax_bg,     colors.syntax_fold_bg, styles.NONE)
Group.new('FoldColumn',   colors.mono_3,        colors.syntax_cursor,  styles.NONE)
Group.new('IncSearch',    colors.hue_6,         colors.none,           styles.NONE)
Group.new('LineNr',       colors.mono_4,        colors.none,           styles.NONE)
Group.new('CursorLineNr', colors.syntax_fg,     colors.syntax_cursor,  styles.NONE)
Group.new('MatchParen',   colors.hue_5,         colors.syntax_cursor,  styles.underline + styles.bold)
Group.new('Italic',       colors.none,          colors.none,           styles.italic)
Group.new('ModeMsg',      colors.syntax_fg,     colors.none,           styles.NONE)
Group.new('MoreMsg',      colors.syntax_fg,     colors.none,           styles.NONE)
Group.new('NonText',      colors.mono_3,        colors.none,           styles.NONE)
Group.new('PMenu',        colors.none,          colors.pmenu,          styles.NONE)
Group.new('PMenuSel',     colors.none,          colors.mono_4,         styles.NONE)
Group.new('PMenuSbar',    colors.none,          colors.syntax_bg,      styles.NONE)
Group.new('PMenuThumb',   colors.none,          colors.mono_1,         styles.NONE)
Group.new('NormalFloat',  colors.none,          colors.pmenu,          styles.NONE)
Group.new('Question',     colors.hue_2,         colors.none,           styles.NONE)
Group.new('Search',       colors.syntax_bg,     colors.hue_6_2,        styles.NONE)
Group.new('SpecialKey',   colors.special_grey,  colors.none,           styles.NONE)
Group.new('Whitespace',   colors.special_grey,  colors.none,           styles.NONE)
Group.new('StatusLine',   colors.syntax_fg,     colors.syntax_cursor,  styles.NONE)
Group.new('StatusLineNC', colors.mono_3,        colors.none,           styles.NONE)
Group.new('TabLine',      colors.mono_2,        colors.visual_grey,    styles.NONE)
Group.new('TabLineFill',  colors.mono_3,        colors.visual_grey,    styles.NONE)
Group.new('TabLineSel',   colors.syntax_bg,     colors.hue_2,          styles.NONE)
Group.new('Title',        colors.syntax_fg,     colors.none,           styles.bold)
Group.new('Visual',       colors.none,          colors.visual_grey,    styles.NONE)
Group.new('VisualNOS',    colors.none,          colors.visual_grey,    styles.NONE)
Group.new('WarningMsg',   colors.hue_5,         colors.none,           styles.NONE)
Group.new('TooLong',      colors.hue_5,         colors.none,           styles.NONE)
Group.new('WildMenu',     colors.syntax_fg,     colors.mono_3,         styles.NONE)
Group.new('SignColumn',   colors.none,          colors.syntax_bg,      styles.NONE)
Group.new('Special',      colors.hue_2,         colors.none,           styles.NONE)

-- Vim Help highlighting
Group.new('helpCommand',      colors.hue_6_2, colors.none, styles.NONE)
Group.new('helpExample',      colors.hue_6_2, colors.none, styles.NONE)
Group.new('helpHeader',       colors.mono_1,  colors.none, styles.bold)
Group.new('helpSectionDelim', colors.mono_3,  colors.none, styles.NONE)

-- Standard syntax highlighting
Group.new('Comment',        colors.mono_3,        colors.none,          styles.italic)
Group.new('Constant',       colors.hue_4,         colors.none,          styles.NONE)
Group.new('String',         colors.hue_4,         colors.none,          styles.NONE)
Group.new('Character',      colors.hue_4,         colors.none,          styles.NONE)
Group.new('Number',         colors.hue_6,         colors.none,          styles.NONE)
Group.new('Boolean',        colors.hue_6,         colors.none,          styles.NONE)
Group.new('Float',          colors.hue_6,         colors.none,          styles.NONE)
Group.new('Identifier',     colors.hue_5,         colors.none,          styles.NONE)
Group.new('Function',       colors.hue_2,         colors.none,          styles.NONE)
Group.new('Statement',      colors.hue_3,         colors.none,          styles.NONE)
Group.new('Conditional',    colors.hue_3,         colors.none,          styles.NONE)
Group.new('Repeat',         colors.hue_3,         colors.none,          styles.NONE)
Group.new('Label',          colors.hue_3,         colors.none,          styles.NONE)
Group.new('Operator',       colors.syntax_accent, colors.none,          styles.NONE)
Group.new('Keyword',        colors.hue_5,         colors.none,          styles.NONE)
Group.new('Exception',      colors.hue_3,         colors.none,          styles.NONE)
Group.new('PreProc',        colors.hue_6_2,       colors.none,          styles.NONE)
Group.new('Include',        colors.hue_2,         colors.none,          styles.NONE)
Group.new('Define',         colors.hue_3,         colors.none,          styles.NONE)
Group.new('Macro',          colors.hue_3,         colors.none,          styles.NONE)
Group.new('PreCondit',      colors.hue_6_2,       colors.none,          styles.NONE)
Group.new('Type',           colors.hue_6_2,       colors.none,          styles.NONE)
Group.new('StorageClass',   colors.hue_6_2,       colors.none,          styles.NONE)
Group.new('Structure',      colors.hue_6_2,       colors.none,          styles.NONE)
Group.new('Typedef',        colors.hue_6_2,       colors.none,          styles.NONE)
Group.new('Special',        colors.hue_2,         colors.none,          styles.NONE)
Group.new('SpecialChar',    colors.none,              colors.none,          styles.NONE)
Group.new('Tag',            colors.none,              colors.none,          styles.NONE)
Group.new('Delimiter',      colors.none,              colors.none,          styles.NONE)
Group.new('SpecialComment', colors.none,              colors.none,          styles.NONE)
Group.new('Debug',          colors.none,              colors.none,          styles.NONE)
Group.new('Underlined',     colors.none,              colors.none,          styles.underline)
Group.new('Ignore',         colors.none,              colors.none,          styles.NONE)
Group.new('Error',          colors.hue_5,         colors.syntax_bg, styles.bold)
Group.new('Todo',           colors.hue_3,         colors.syntax_bg, styles.NONE)

-- Diff highlighting
Group.new('DiffAdd',     colors.hue_4, colors.visual_grey, styles.NONE)
Group.new('DiffChange',  colors.hue_6, colors.visual_grey, styles.NONE)
Group.new('DiffDelete',  colors.hue_5, colors.visual_grey, styles.NONE)
Group.new('DiffText',    colors.hue_2, colors.visual_grey, styles.NONE)
Group.new('DiffAdded',   colors.hue_4, colors.visual_grey, styles.NONE)
Group.new('DiffFile',    colors.hue_5, colors.visual_grey, styles.NONE)
Group.new('DiffNewFile', colors.hue_4, colors.visual_grey, styles.NONE)
Group.new('DiffLine',    colors.hue_2, colors.visual_grey, styles.NONE)
Group.new('DiffRemoved', colors.hue_5, colors.visual_grey, styles.NONE)

-- Asciidoc highlighting
Group.new('asciidocListingBlock',   colors.mono_2,  colors.none, styles.NONE)

-- C/C++ highlighting
Group.new('cInclude',           colors.hue_3,  colors.none, styles.NONE)
Group.new('cPreCondit',         colors.hue_3,  colors.none, styles.NONE)
Group.new('cPreConditMatch',    colors.hue_3,  colors.none, styles.NONE)

Group.new('cType',              colors.hue_3,  colors.none, styles.NONE)
Group.new('cStorageClass',      colors.hue_3,  colors.none, styles.NONE)
Group.new('cStructure',         colors.hue_3,  colors.none, styles.NONE)
Group.new('cOperator',          colors.hue_3,  colors.none, styles.NONE)
Group.new('cStatement',         colors.hue_3,  colors.none, styles.NONE)
Group.new('cTODO',              colors.hue_3,  colors.none, styles.NONE)
Group.new('cConstant',          colors.hue_6,  colors.none, styles.NONE)
Group.new('cSpecial',           colors.hue_1,  colors.none, styles.NONE)
Group.new('cSpecialCharacter',  colors.hue_1,  colors.none, styles.NONE)
Group.new('cString',            colors.hue_4,  colors.none, styles.NONE)

Group.new('cppType',            colors.hue_3,  colors.none, styles.NONE)
Group.new('cppStorageClass',    colors.hue_3,  colors.none, styles.NONE)
Group.new('cppStructure',       colors.hue_3,  colors.none, styles.NONE)
Group.new('cppModifier',        colors.hue_3,  colors.none, styles.NONE)
Group.new('cppOperator',        colors.hue_3,  colors.none, styles.NONE)
Group.new('cppAccess',          colors.hue_3,  colors.none, styles.NONE)
Group.new('cppStatement',       colors.hue_3,  colors.none, styles.NONE)
Group.new('cppConstant',        colors.hue_5,  colors.none, styles.NONE)
Group.new('cCppString',         colors.hue_4,  colors.none, styles.NONE)

-- Cucumber highlighting
Group.new('cucumberGiven',           colors.hue_2,  colors.none, styles.NONE)
Group.new('cucumberWhen',            colors.hue_2,  colors.none, styles.NONE)
Group.new('cucumberWhenAnd',         colors.hue_2,  colors.none, styles.NONE)
Group.new('cucumberThen',            colors.hue_2,  colors.none, styles.NONE)
Group.new('cucumberThenAnd',         colors.hue_2,  colors.none, styles.NONE)
Group.new('cucumberUnparsed',        colors.hue_6,  colors.none, styles.NONE)
Group.new('cucumberFeature',         colors.hue_5,  colors.none, styles.bold)
Group.new('cucumberBackground',      colors.hue_3,  colors.none, styles.bold)
Group.new('cucumberScenario',        colors.hue_3,  colors.none, styles.bold)
Group.new('cucumberScenarioOutline', colors.hue_3,  colors.none, styles.bold)
Group.new('cucumberTags',            colors.mono_3, colors.none, styles.bold)
Group.new('cucumberDelimiter',       colors.mono_3, colors.none, styles.bold)

-- Man
Group.new('manTitle',  groups.String, groups.String,    groups.String)
Group.new('manFooter', colors.mono_3, colors.none, styles.NONE)

-- CSS/Sass highlighting
Group.new('cssAttrComma',         colors.hue_3,  colors.none, styles.NONE)
Group.new('cssAttributeSelector', colors.hue_4,  colors.none, styles.NONE)
Group.new('cssBraces',            colors.mono_2, colors.none, styles.NONE)
Group.new('cssClassName',         colors.hue_6,  colors.none, styles.NONE)
Group.new('cssClassNameDot',      colors.hue_6,  colors.none, styles.NONE)
Group.new('cssDefinition',        colors.hue_3,  colors.none, styles.NONE)
Group.new('cssFontAttr',          colors.hue_6,  colors.none, styles.NONE)
Group.new('cssFontDescriptor',    colors.hue_3,  colors.none, styles.NONE)
Group.new('cssFunctionName',      colors.hue_2,  colors.none, styles.NONE)
Group.new('cssIdentifier',        colors.hue_2,  colors.none, styles.NONE)
Group.new('cssImportant',         colors.hue_3,  colors.none, styles.NONE)
Group.new('cssInclude',           colors.mono_1, colors.none, styles.NONE)
Group.new('cssIncludeKeyword',    colors.hue_3,  colors.none, styles.NONE)
Group.new('cssMediaType',         colors.hue_6,  colors.none, styles.NONE)
Group.new('cssProp',              colors.hue_1,  colors.none, styles.NONE)
Group.new('cssPseudoClassId',     colors.hue_6,  colors.none, styles.NONE)
Group.new('cssSelectorOp',        colors.hue_3,  colors.none, styles.NONE)
Group.new('cssSelectorOp2',       colors.hue_3,  colors.none, styles.NONE)
Group.new('cssStringQ',           colors.hue_4,  colors.none, styles.NONE)
Group.new('cssStringQQ',          colors.hue_4,  colors.none, styles.NONE)
Group.new('cssTagName',           colors.hue_5,  colors.none, styles.NONE)
Group.new('cssAttr',              colors.hue_6,  colors.none, styles.NONE)

Group.new('sassAmpersand',      colors.hue_5,   colors.none, styles.NONE)
Group.new('sassClass',          colors.hue_6_2, colors.none, styles.NONE)
Group.new('sassControl',        colors.hue_3,   colors.none, styles.NONE)
Group.new('sassExtend',         colors.hue_3,   colors.none, styles.NONE)
Group.new('sassFor',            colors.mono_1,  colors.none, styles.NONE)
Group.new('sassProperty',       colors.hue_1,   colors.none, styles.NONE)
Group.new('sassFunction',       colors.hue_1,   colors.none, styles.NONE)
Group.new('sassId',             colors.hue_2,   colors.none, styles.NONE)
Group.new('sassInclude',        colors.hue_3,   colors.none, styles.NONE)
Group.new('sassMedia',          colors.hue_3,   colors.none, styles.NONE)
Group.new('sassMediaOperators', colors.mono_1,  colors.none, styles.NONE)
Group.new('sassMixin',          colors.hue_3,   colors.none, styles.NONE)
Group.new('sassMixinName',      colors.hue_2,   colors.none, styles.NONE)
Group.new('sassMixing',         colors.hue_3,   colors.none, styles.NONE)

Group.new('scssSelectorName',   colors.hue_6_2, colors.none, styles.NONE)

-- Elixir highlighting
Group.new('elixirModule',            groups.Define,  groups.Define)
Group.new('elixirAlias',             colors.hue_6_2, colors.none, styles.NONE)
Group.new('elixirAtom',              colors.hue_1,   colors.none, styles.NONE)
Group.new('elixirBlockDefinition',   colors.hue_3,   colors.none, styles.NONE)
Group.new('elixirModuleDeclaration', colors.hue_6,   colors.none, styles.NONE)
Group.new('elixirInclude',           colors.hue_5,   colors.none, styles.NONE)
Group.new('elixirOperator',          colors.hue_6,   colors.none, styles.NONE)

-- Git and git related plugins highlighting
Group.new('gitcommitComment',       colors.mono_3,  colors.none, styles.NONE)
Group.new('gitcommitUnmerged',      colors.hue_4,   colors.none, styles.NONE)
Group.new('gitcommitOnBranch',      colors.none,        colors.none, styles.NONE)
Group.new('gitcommitBranch',        colors.hue_3,   colors.none, styles.NONE)
Group.new('gitcommitDiscardedType', colors.hue_5,   colors.none, styles.NONE)
Group.new('gitcommitSelectedType',  colors.hue_4,   colors.none, styles.NONE)
Group.new('gitcommitHeader',        colors.none,        colors.none, styles.NONE)
Group.new('gitcommitUntrackedFile', colors.hue_1,   colors.none, styles.NONE)
Group.new('gitcommitDiscardedFile', colors.hue_5,   colors.none, styles.NONE)
Group.new('gitcommitSelectedFile',  colors.hue_4,   colors.none, styles.NONE)
Group.new('gitcommitUnmergedFile',  colors.hue_6_2, colors.none, styles.NONE)
Group.new('gitcommitFile',          colors.none,        colors.none, styles.NONE)
Group.new('gitcommitNoBranch',      groups.gitcommitBranch,        groups.gitcommitBranch,        groups.gitcommitBranch)
Group.new('gitcommitUntracked',     groups.gitcommitComment,       groups.gitcommitComment,       groups.gitcommitComment)
Group.new('gitcommitDiscarded',     groups.gitcommitComment,       groups.gitcommitComment,       groups.gitcommitComment)
Group.new('gitcommitDiscardedArrow',groups.gitcommitDiscardedFile, groups.gitcommitDiscardedFile, groups.gitcommitDiscardedFile)
Group.new('gitcommitSelectedArrow', groups.gitcommitSelectedFile,  groups.gitcommitSelectedFile,  groups.gitcommitSelectedFile)
Group.new('gitcommitUnmergedArrow', groups.gitcommitUnmergedFile,  groups.gitcommitUnmergedFile,  groups.gitcommitUnmergedFile)
Group.new('SignifySignAdd',         colors.hue_4,   colors.none, styles.NONE)
Group.new('SignifySignChange',      colors.hue_6_2, colors.none, styles.NONE)
Group.new('SignifySignDelete',      colors.hue_5,   colors.none, styles.NONE)
Group.new('GitGutterAdd',           groups.SignifySignAdd,         groups.SignifySignAdd,         groups.SignifySignAdd)
Group.new('GitGutterChange',        groups.SignifySignChange,      groups.SignifySignChange,      groups.SignifySignChange)
Group.new('GitGutterDelete',        groups.SignifySignDelete,      groups.SignifySignDelete,      groups.SignifySignDelete)
Group.new('diffAdded',              colors.hue_4,   colors.none, styles.NONE)
Group.new('diffRemoved',            colors.hue_5,   colors.none, styles.NONE)

-- Go highlighting
Group.new('goDeclaration',         colors.hue_3, colors.none, styles.NONE)
Group.new('goField',               colors.hue_5, colors.none, styles.NONE)
Group.new('goMethod',              colors.hue_1, colors.none, styles.NONE)
Group.new('goType',                colors.hue_3, colors.none, styles.NONE)
Group.new('goUnsignedInts',        colors.hue_1, colors.none, styles.NONE)

-- Haskell highlighting
Group.new('haskellDeclKeyword',    colors.hue_2, colors.none, styles.NONE)
Group.new('haskellType',           colors.hue_4, colors.none, styles.NONE)
Group.new('haskellWhere',          colors.hue_5, colors.none, styles.NONE)
Group.new('haskellImportKeywords', colors.hue_2, colors.none, styles.NONE)
Group.new('haskellOperators',      colors.hue_5, colors.none, styles.NONE)
Group.new('haskellDelimiter',      colors.hue_2, colors.none, styles.NONE)
Group.new('haskellIdentifier',     colors.hue_6, colors.none, styles.NONE)
Group.new('haskellKeyword',        colors.hue_5, colors.none, styles.NONE)
Group.new('haskellNumber',         colors.hue_1, colors.none, styles.NONE)
Group.new('haskellString',         colors.hue_1, colors.none, styles.NONE)

-- HTML highlighting
Group.new('htmlArg',            colors.hue_6,  colors.none, styles.NONE)
Group.new('htmlTagName',        colors.hue_5,  colors.none, styles.NONE)
Group.new('htmlTagN',           colors.hue_5,  colors.none, styles.NONE)
Group.new('htmlSpecialTagName', colors.hue_5,  colors.none, styles.NONE)
Group.new('htmlTag',            colors.mono_2, colors.none, styles.NONE)
Group.new('htmlEndTag',         colors.mono_2, colors.none, styles.NONE)

Group.new('MatchTag', colors.hue_5, colors.syntax_cursor, styles.underline + styles.bold)

-- JavaScript highlighting
Group.new('coffeeString',           colors.hue_4,   colors.none, styles.NONE)

Group.new('javaScriptBraces',       colors.mono_2,  colors.none, styles.NONE)
Group.new('javaScriptFunction',     colors.hue_3,   colors.none, styles.NONE)
Group.new('javaScriptIdentifier',   colors.hue_3,   colors.none, styles.NONE)
Group.new('javaScriptNull',         colors.hue_6,   colors.none, styles.NONE)
Group.new('javaScriptNumber',       colors.hue_6,   colors.none, styles.NONE)
Group.new('javaScriptRequire',      colors.hue_1,   colors.none, styles.NONE)
Group.new('javaScriptReserved',     colors.hue_3,   colors.none, styles.NONE)

-- https://github.com/pangloss/vim-javascript
Group.new('jsArrowFunction',        colors.hue_3,   colors.none, styles.NONE)
Group.new('jsBraces',               colors.mono_2,  colors.none, styles.NONE)
Group.new('jsClassBraces',          colors.mono_2,  colors.none, styles.NONE)
Group.new('jsClassKeywords',        colors.hue_3,   colors.none, styles.NONE)
Group.new('jsDocParam',             colors.hue_2,   colors.none, styles.NONE)
Group.new('jsDocTags',              colors.hue_3,   colors.none, styles.NONE)
Group.new('jsFuncBraces',           colors.mono_2,  colors.none, styles.NONE)
Group.new('jsFuncCall',             colors.hue_2,   colors.none, styles.NONE)
Group.new('jsFuncParens',           colors.mono_2,  colors.none, styles.NONE)
Group.new('jsFunction',             colors.hue_3,   colors.none, styles.NONE)
Group.new('jsGlobalObjects',        colors.hue_6_2, colors.none, styles.NONE)
Group.new('jsModuleWords',          colors.hue_3,   colors.none, styles.NONE)
Group.new('jsModules',              colors.hue_3,   colors.none, styles.NONE)
Group.new('jsNoise',                colors.mono_2,  colors.none, styles.NONE)
Group.new('jsNull',                 colors.hue_6,   colors.none, styles.NONE)
Group.new('jsOperator',             colors.hue_3,   colors.none, styles.NONE)
Group.new('jsParens',               colors.mono_2,  colors.none, styles.NONE)
Group.new('jsStorageClass',         colors.hue_3,   colors.none, styles.NONE)
Group.new('jsTemplateBraces',       colors.hue_5_2, colors.none, styles.NONE)
Group.new('jsTemplateVar',          colors.hue_4,   colors.none, styles.NONE)
Group.new('jsThis',                 colors.hue_5,   colors.none, styles.NONE)
Group.new('jsUndefined',            colors.hue_6,   colors.none, styles.NONE)
Group.new('jsObjectValue',          colors.hue_2,   colors.none, styles.NONE)
Group.new('jsObjectKey',            colors.hue_1,   colors.none, styles.NONE)
Group.new('jsReturn',               colors.hue_3,   colors.none, styles.NONE)

-- https://github.com/othree/yajs.vim
Group.new('javascriptArrowFunc',    colors.hue_3,   colors.none, styles.NONE)
Group.new('javascriptClassExtends', colors.hue_3,   colors.none, styles.NONE)
Group.new('javascriptClassKeyword', colors.hue_3,   colors.none, styles.NONE)
Group.new('javascriptDocNotation',  colors.hue_3,   colors.none, styles.NONE)
Group.new('javascriptDocParamName', colors.hue_2,   colors.none, styles.NONE)
Group.new('javascriptDocTags',      colors.hue_3,   colors.none, styles.NONE)
Group.new('javascriptEndColons',    colors.mono_3,  colors.none, styles.NONE)
Group.new('javascriptExport',       colors.hue_3,   colors.none, styles.NONE)
Group.new('javascriptFuncArg',      colors.mono_1,  colors.none, styles.NONE)
Group.new('javascriptFuncKeyword',  colors.hue_3,   colors.none, styles.NONE)
Group.new('javascriptIdentifier',   colors.hue_5,   colors.none, styles.NONE)
Group.new('javascriptImport',       colors.hue_3,   colors.none, styles.NONE)
Group.new('javascriptObjectLabel',  colors.mono_1,  colors.none, styles.NONE)
Group.new('javascriptOpSymbol',     colors.hue_1,   colors.none, styles.NONE)
Group.new('javascriptOpSymbols',    colors.hue_1,   colors.none, styles.NONE)
Group.new('javascriptPropertyName', colors.hue_4,   colors.none, styles.NONE)
Group.new('javascriptTemplateSB',   colors.hue_5_2, colors.none, styles.NONE)
Group.new('javascriptVariable',     colors.hue_3,   colors.none, styles.NONE)

-- JSON highlighting
Group.new('jsonCommentError',         colors.mono_1,  colors.none, styles.NONE)
Group.new('jsonKeyword',              colors.hue_5,   colors.none, styles.NONE)
Group.new('jsonQuote',                colors.mono_3,  colors.none, styles.NONE)
Group.new('jsonTrailingCommaError',   colors.hue_5,   colors.none, styles.reverse)
Group.new('jsonMissingCommaError',    colors.hue_5,   colors.none, styles.reverse)
Group.new('jsonNoQuotesError',        colors.hue_5,   colors.none, styles.reverse)
Group.new('jsonNumError',             colors.hue_5,   colors.none, styles.reverse)
Group.new('jsonString',               colors.hue_4,   colors.none, styles.NONE)
Group.new('jsonBoolean',              colors.hue_3,   colors.none, styles.NONE)
Group.new('jsonNumber',               colors.hue_6,   colors.none, styles.NONE)
Group.new('jsonStringSQError',        colors.hue_5,   colors.none, styles.reverse)
Group.new('jsonSemicolonError',       colors.hue_5,   colors.none, styles.reverse)

-- Markdown highlighting ---------------------------------------------------{{{
Group.new('markdownUrl',              colors.mono_3,  colors.none, styles.NONE)
Group.new('markdownBold',             colors.hue_6,   colors.none, styles.bold)
Group.new('markdownItalic',           colors.hue_6,   colors.none, styles.bold)
Group.new('markdownCode',             colors.hue_4,   colors.none, styles.NONE)
Group.new('markdownCodeBlock',        colors.hue_5,   colors.none, styles.NONE)
Group.new('markdownCodeDelimiter',    colors.hue_4,   colors.none, styles.NONE)
Group.new('markdownHeadingDelimiter', colors.hue_5_2, colors.none, styles.NONE)
Group.new('markdownH1',               colors.hue_5,   colors.none, styles.NONE)
Group.new('markdownH2',               colors.hue_5,   colors.none, styles.NONE)
Group.new('markdownH3',               colors.hue_5,   colors.none, styles.NONE)
Group.new('markdownH3',               colors.hue_5,   colors.none, styles.NONE)
Group.new('markdownH4',               colors.hue_5,   colors.none, styles.NONE)
Group.new('markdownH5',               colors.hue_5,   colors.none, styles.NONE)
Group.new('markdownH6',               colors.hue_5,   colors.none, styles.NONE)
Group.new('markdownListMarker',       colors.hue_5,   colors.none, styles.NONE)

-- PHP highlighting
Group.new('phpClass',        colors.hue_6_2, colors.none, styles.NONE)
Group.new('phpFunction',     colors.hue_2,   colors.none, styles.NONE)
Group.new('phpFunctions',    colors.hue_2,   colors.none, styles.NONE)
Group.new('phpInclude',      colors.hue_3,   colors.none, styles.NONE)
Group.new('phpKeyword',      colors.hue_3,   colors.none, styles.NONE)
Group.new('phpParent',       colors.mono_3,  colors.none, styles.NONE)
Group.new('phpType',         colors.hue_3,   colors.none, styles.NONE)
Group.new('phpSuperGlobals', colors.hue_5,   colors.none, styles.NONE)

-- Pug (Formerly Jade) highlighting
Group.new('pugAttributesDelimiter',   colors.hue_6,    colors.none, styles.NONE)
Group.new('pugClass',                 colors.hue_6,    colors.none, styles.NONE)
Group.new('pugDocType',               colors.mono_3,   colors.none, styles.italic)
Group.new('pugTag',                   colors.hue_5,    colors.none, styles.NONE)

-- PureScript highlighting
Group.new('purescriptKeyword',          colors.hue_3,     colors.none, styles.NONE)
Group.new('purescriptModuleName',       colors.syntax_fg, colors.none, styles.NONE)
Group.new('purescriptIdentifier',       colors.syntax_fg, colors.none, styles.NONE)
Group.new('purescriptType',             colors.hue_6_2,   colors.none, styles.NONE)
Group.new('purescriptTypeVar',          colors.hue_5,     colors.none, styles.NONE)
Group.new('purescriptConstructor',      colors.hue_5,     colors.none, styles.NONE)
Group.new('purescriptOperator',         colors.syntax_fg, colors.none, styles.NONE)

-- Python highlighting
Group.new('pythonImport',               colors.hue_3,     colors.none, styles.NONE)
Group.new('pythonBuiltin',              colors.hue_1,     colors.none, styles.NONE)
Group.new('pythonStatement',            colors.hue_3,     colors.none, styles.NONE)
Group.new('pythonParam',                colors.hue_6,     colors.none, styles.NONE)
Group.new('pythonEscape',               colors.hue_5,     colors.none, styles.NONE)
Group.new('pythonSelf',                 colors.mono_2,    colors.none, styles.italic)
Group.new('pythonClass',                colors.hue_2,     colors.none, styles.NONE)
Group.new('pythonOperator',             colors.hue_3,     colors.none, styles.NONE)
Group.new('pythonEscape',               colors.hue_5,     colors.none, styles.NONE)
Group.new('pythonFunction',             colors.hue_2,     colors.none, styles.NONE)
Group.new('pythonKeyword',              colors.hue_2,     colors.none, styles.NONE)
Group.new('pythonModule',               colors.hue_3,     colors.none, styles.NONE)
Group.new('pythonStringDelimiter',      colors.hue_4,     colors.none, styles.NONE)
Group.new('pythonSymbol',               colors.hue_1,     colors.none, styles.NONE)

-- Ruby highlighting -------------------------------------------------------{{{
Group.new('rubyBlock',                     colors.hue_3,   colors.none, styles.NONE)
Group.new('rubyBlockParameter',            colors.hue_5,   colors.none, styles.NONE)
Group.new('rubyBlockParameterList',        colors.hue_5,   colors.none, styles.NONE)
Group.new('rubyCapitalizedMethod',         colors.hue_3,   colors.none, styles.NONE)
Group.new('rubyClass',                     colors.hue_3,   colors.none, styles.NONE)
Group.new('rubyConstant',                  colors.hue_6_2, colors.none, styles.NONE)
Group.new('rubyControl',                   colors.hue_3,   colors.none, styles.NONE)
Group.new('rubyDefine',                    colors.hue_3,   colors.none, styles.NONE)
Group.new('rubyEscape',                    colors.hue_5,   colors.none, styles.NONE)
Group.new('rubyFunction',                  colors.hue_2,   colors.none, styles.NONE)
Group.new('rubyGlobalVariable',            colors.hue_5,   colors.none, styles.NONE)
Group.new('rubyInclude',                   colors.hue_2,   colors.none, styles.NONE)
Group.new('rubyIncluderubyGlobalVariable', colors.hue_5,   colors.none, styles.NONE)
Group.new('rubyInstanceVariable',          colors.hue_5,   colors.none, styles.NONE)
Group.new('rubyInterpolation',             colors.hue_1,   colors.none, styles.NONE)
Group.new('rubyInterpolationDelimiter',    colors.hue_5,   colors.none, styles.NONE)
Group.new('rubyKeyword',                   colors.hue_2,   colors.none, styles.NONE)
Group.new('rubyModule',                    colors.hue_3,   colors.none, styles.NONE)
Group.new('rubyPseudoVariable',            colors.hue_5,   colors.none, styles.NONE)
Group.new('rubyRegexp',                    colors.hue_1,   colors.none, styles.NONE)
Group.new('rubyRegexpDelimiter',           colors.hue_1,   colors.none, styles.NONE)
Group.new('rubyStringDelimiter',           colors.hue_4,   colors.none, styles.NONE)
Group.new('rubySymbol',                    colors.hue_1,   colors.none, styles.NONE)

-- Spelling highlighting
Group.new('SpellBad',     colors.none, colors.syntax_bg, styles.undercurl)
Group.new('SpellLocal',   colors.none, colors.syntax_bg, styles.undercurl)
Group.new('SpellCap',     colors.none, colors.syntax_bg, styles.undercurl)
Group.new('SpellRare',    colors.none, colors.syntax_bg, styles.undercurl)

-- Vim highlighting
Group.new('vimCommand',      colors.hue_3,  colors.none, styles.NONE)
Group.new('vimCommentTitle', colors.mono_3, colors.none, styles.bold)
Group.new('vimFunction',     colors.hue_1,  colors.none, styles.NONE)
Group.new('vimFuncName',     colors.hue_3,  colors.none, styles.NONE)
Group.new('vimHighlight',    colors.hue_2,  colors.none, styles.NONE)
Group.new('vimLineComment',  colors.mono_3, colors.none, styles.italic)
Group.new('vimParenSep',     colors.mono_2, colors.none, styles.NONE)
Group.new('vimSep',          colors.mono_2, colors.none, styles.NONE)
Group.new('vimUserFunc',     colors.hue_1,  colors.none, styles.NONE)
Group.new('vimVar',          colors.hue_5,  colors.none, styles.NONE)

-- XML highlighting
Group.new('xmlAttrib',  colors.hue_6_2, colors.none, styles.NONE)
Group.new('xmlEndTag',  colors.hue_5,   colors.none, styles.NONE)
Group.new('xmlTag',     colors.hue_5,   colors.none, styles.NONE)
Group.new('xmlTagName', colors.hue_5,   colors.none, styles.NONE)

-- ZSH highlighting
Group.new('zshCommands',     colors.syntax_fg, colors.none, styles.NONE)
Group.new('zshDeref',        colors.hue_5,     colors.none, styles.NONE)
Group.new('zshShortDeref',   colors.hue_5,     colors.none, styles.NONE)
Group.new('zshFunction',     colors.hue_1,     colors.none, styles.NONE)
Group.new('zshKeyword',      colors.hue_3,     colors.none, styles.NONE)
Group.new('zshSubst',        colors.hue_5,     colors.none, styles.NONE)
Group.new('zshSubstDelim',   colors.mono_3,    colors.none, styles.NONE)
Group.new('zshTypes',        colors.hue_3,     colors.none, styles.NONE)
Group.new('zshVariableDef',  colors.hue_6,     colors.none, styles.NONE)

-- Rust highlighting
Group.new('rustExternCrate',          colors.hue_5,  colors.none, styles.bold)
Group.new('rustIdentifier',           colors.hue_2,  colors.none, styles.NONE)
Group.new('rustDeriveTrait',          colors.hue_4,  colors.none, styles.NONE)
Group.new('SpecialComment',           colors.mono_3, colors.none, styles.NONE)
Group.new('rustCommentLine',          colors.mono_3, colors.none, styles.NONE)
Group.new('rustCommentLineDoc',       colors.mono_3, colors.none, styles.NONE)
Group.new('rustCommentLineDocError',  colors.mono_3, colors.none, styles.NONE)
Group.new('rustCommentBlock',         colors.mono_3, colors.none, styles.NONE)
Group.new('rustCommentBlockDoc',      colors.mono_3, colors.none, styles.NONE)
Group.new('rustCommentBlockDocError', colors.mono_3, colors.none, styles.NONE)
